spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SimplyAccounting?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: 
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9090
simplyaccounting:
  app:
    jwt:
      secret: 
      expiration: 36000000