spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SimplyAccounting?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: fc15f3c9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9090
simplyaccounting:
  app:
    jwtSecret: secret
    jwtExpiration: 36000000